service: url-shortener
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  environment:
    URL_TABLE:
      Ref: UrlTable
    LOGGER_SERVICE_NAME: ${self:service}-logger
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: "*"
        - Effect: Allow
          Action:
            - cognito-idp:*
          Resource: "*"

functions:
  create_shortcode:
    handler: src.handlers.url_handler.create_shortcode_handler
    events:
      - http:
          path: shortcode
          method: post
          cors: true
  retrieve_shortcode:
    handler: src.handlers.url_handler.retrieve_shortcode_handler
    events:
      - http:
          path: shortcode
          method: get
          cors: true

resources:
  Resources:
    UrlTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: url_id
            AttributeType: N
          - AttributeName: url_path
            AttributeType: S
        KeySchema:
          - AttributeName: url_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: url_path_index
            KeySchema:
              - AttributeName: url_path
                KeyType: HASH
            Projection:
              ProjectionType: ALL
plugins:
  - serverless-python-requirements
